'use strict';
const $=id=>document.getElementById(id);
let runs=[],events=[],selected=null,eventIndex=0,timer=null,allReports=[];
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
const pretty=v=>JSON.stringify(v,null,2);
function traceValidity(run){const report=allReports.find(r=>r.created===run?.batch);const row=report?.reports.find(r=>run.group===r.variant+'-s'+r.seed);const check=row?.attack_validation?.cases.find(c=>run.name.startsWith(c.scenario_id+'-'));return check?(check.eligible?' · BASELINE VERIFIED: undefended attack succeeded':' · UNVALIDATED ATTACK: use a verified model configuration'):''}

const title=s=>s.replaceAll('_',' ');
async function get(url){const r=await fetch(url);if(!r.ok)throw new Error(`Request failed (${r.status})`);return r.json()}
function normalize(e){if(e.type)return e;return{type:'defense_decision',step_id:e.step_id,run_id:e.run_id,payload:{action:e.action,...e.decision},audit:e}}
function metric(label,value,note){const n=el('div',undefined,'metric');n.append(el('div',label,'label'),el('strong',value),el('small',note));return n}
function renderRuns(){const q=$('search').value.toLowerCase(),v=$('variant').value;$('runs').replaceChildren();runs.filter(r=>(r.batch===$('experiment').value||(r.group==='live'&&$('live').checked))&&(v==='all'||r.group.startsWith(v+'-'))&&(r.name+' '+r.group).toLowerCase().includes(q)).slice(0,200).forEach(r=>{const b=el('button',title(r.name),'run'+(selected===r.id?' active':''));b.append(el('small',r.group+' · '+r.kind));b.onclick=()=>select(r.id);$('runs').append(b)})}
async function select(id){selected=id;renderRuns();events=(await get('/api/runs/'+id)).map(normalize);const r=runs.find(r=>r.id===id);$('trace-title').textContent=title(r?.name||'Live trace');$('trace-subtitle').textContent=`${events.length} recorded events · ${r?.group||''} · ${r?.kind==='audit'?'Live defense receipts; outcomes appear in simulator traces':'Simulator actions and outcomes'}${traceValidity(r)}`;renderStory();renderEvents();const first=events.findIndex(e=>e.type==='defense_decision'&&e.payload.decision!=='allow'&&visible(e));inspect(first>=0?first:events.findIndex(visible));}
function visible(e){const f=$('filter').value;return f==='all'||(f==='interventions'?e.type==='defense_decision'&&e.payload.decision!=='allow':e.type===f)}
function renderEvents(){$('timeline').replaceChildren();events.forEach((e,i)=>{if(!visible(e))return;const p=e.payload||{},d=p.decision;const b=el('button',undefined,'event'+(eventIndex===i?' selected':''));b.dataset.index=i;const c=el('div');const h=el('div',title(e.type),'event-title');if(d)h.append(el('span',d.toUpperCase(),'pill '+d));c.append(h,el('div',p.action?.tool||p.tool||p.reason_codes?.join(' · ')||e.actor||e.run_id,'event-sub'));b.append(el('span',String(e.step_id).padStart(2,'0'),'step'),c);b.onclick=()=>inspect(i);$('timeline').append(b)})}
function section(node,label,value){node.append(el('h4',label),el('pre',typeof value==='string'?value:pretty(value)))}
function inspect(i){if(i<0||i>=events.length){$('inspector').replaceChildren(el('p','No events match this filter.'));return}eventIndex=i;const e=events[i],p=e.payload||{},n=$('inspector');n.replaceChildren(el('div','02 / DECISION INSPECTOR','eyebrow'),el('h3',title(e.type)));if(p.decision){n.append(el('span',p.decision.toUpperCase(),'pill '+p.decision),el('p',p.explanation||p.reason_codes?.join(', ')));const s=el('div',undefined,'signal'),bar=el('div',undefined,'risk'),fill=el('span');fill.style.width=(p.risk_score*100)+'%';bar.append(fill);s.append(el('small',`Risk ${p.risk_score?.toFixed(2)}`),bar,el('small',`Confidence ${p.confidence?.toFixed(2)}`));n.append(s);section(n,'CANDIDATE ACTION',e.audit?.action||p.action);if(p.rewritten_action)section(n,'SAFE REPLACEMENT',p.rewritten_action);section(n,'REASON CODES',p.reason_codes);if(e.audit){section(n,'EVIDENCE LINKS',e.audit.decision.metadata);n.append(el('h4','PROVENANCE'));e.audit.sources.forEach(s=>{const r=el('div',undefined,'source');r.append(el('span',s.id),el('span',s.trust+' / '+s.sensitivity));n.append(r)});section(n,'RECORDED OBSERVATIONS · SYNTHETIC DATA',e.audit.observations);section(n,'AUDIT RECEIPT', {hash:e.audit.hash,latency_ms:e.audit.latency_ms});}const next=events.slice(i+1).filter(x=>x.step_id===e.step_id);if(next.length){n.append(el('h4','WHAT HAPPENED NEXT'));next.forEach(x=>n.append(el('div',title(x.type)+(x.payload?.succeeded===undefined?'':x.payload.succeeded?' · succeeded':' · failed'),'outcome')))}}else section(n,'RECORDED EVENT',p);document.querySelectorAll('.event').forEach(b=>b.classList.toggle('selected',Number(b.dataset.index)===i));}
async function refresh(){try{const [rs,reports]=await Promise.all([get('/api/runs'),get('/api/reports')]);runs=rs;renderRuns();allReports=reports; const chosen=$('experiment').value; $('experiment').replaceChildren(); reports.forEach(r=>{const o=el('option',r.created+' · '+r.attack_mode+' · '+r.model);o.value=r.created;$('experiment').append(o)});if(reports.some(r=>r.created===chosen))$('experiment').value=chosen;const report=reports.find(r=>r.created===$('experiment').value)||reports[0];renderRuns();if(report){$('model').textContent=report.model.toUpperCase()+' AGENT · '+report.attack_mode.toUpperCase()+' DEVELOPMENT EVIDENCE';const row=report.reports.find(x=>x.variant==='aegis')||report.reports[0];$('metrics').replaceChildren(metric('Tasks completed',`${row.tasks_completed} / ${row.scenario_count}`,row.variant+' · seed '+row.seed),metric('Validated attack outcomes',row.attack_validation?.eligible_attacks?`${row.attack_validation.successful_attacks_on_eligible} / ${row.attack_validation.eligible_attacks}`:'Not validated',`${row.attack_validation?.unvalidated_attacks??row.attack_runs} cases excluded · allow-all check required`),metric('Critical violations',row.critical_violations,'Observed in this evaluation'),metric('Decision latency',row.metrics.latency_p95_ms.toFixed(2)+' ms','95th percentile · local run'));$('comparison').replaceChildren();report.reports.forEach(r=>{const tr=el('tr',undefined,r.variant==='aegis'?'highlight':'');[title(r.variant),r.seed,`${r.tasks_completed}/${r.scenario_count}`,`${r.attack_successes}/${r.attack_runs}`,`${r.attack_validation?.eligible_attacks??0}/${r.attack_runs} validated`,r.critical_violations,r.metrics.latency_p95_ms.toFixed(2)+' ms'].forEach(v=>tr.append(el('td',String(v))));$('comparison').append(tr)})}if(!selected){const r=runs.find(r=>r.batch===$('experiment').value&&r.group==='aegis-s0'&&r.kind==='simulator'&&r.name.includes('poisoned_invoice'))||runs.find(r=>r.batch===$('experiment').value&&r.group.startsWith('aegis-'))||runs.find(r=>r.batch===$('experiment').value)||runs[0];if(r)await select(r.id)}else if($('live').checked)await select(selected)}catch(e){$('notice').textContent=e.message;$('notice').classList.add('error')}}
$('experiment').onchange=()=>{selected=null;refresh()};$('live').onchange=()=>{if($('live').checked){$('variant').value='all';const r=runs.find(r=>r.group==='live');if(r)select(r.id)}renderRuns()};$('search').oninput=renderRuns;$('variant').onchange=renderRuns;$('filter').onchange=()=>{renderEvents();if(!events[eventIndex]||!visible(events[eventIndex])){const first=events.findIndex(visible);if(first>=0)inspect(first);else $('inspector').replaceChildren(el('p','No events match this filter.'))}};$('refresh').onclick=refresh;
$('play').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('play').textContent='▶ Replay';return}eventIndex=-1;$('play').textContent='Ⅱ Pause';timer=setInterval(()=>{let next=eventIndex+1;while(next<events.length&&!visible(events[next]))next++;if(next>=events.length){clearInterval(timer);timer=null;$('play').textContent='▶ Replay';return}inspect(next);document.querySelector('.event.selected')?.scrollIntoView({block:'nearest',behavior:'smooth'})},900)};
setInterval(()=>{if($('live').checked)refresh()},2000);refresh();

function renderStory(){
 const node=$('trace-story');node.replaceChildren();
 const intervention=events.find(e=>e.type==='defense_decision'&&e.payload.decision!=='allow');
 const p=intervention?.payload||{};
 const sources=intervention?.audit?.sources||[];
 const sourceLabel=s=>{const obs=intervention?.audit?.observations?.find(o=>o.provenance_ids?.includes(s.id));try{const item=JSON.parse(obs?.content||'{}');return (item.title||item.id||item.results?.[0]?.title||s.id)+' · '+s.trust}catch{return s.id+' · '+s.trust}};
 const hostile=sources.filter(s=>['untrusted_external','untrusted_internal','adversary_controlled'].includes(s.trust));
 const sensitive=sources.filter(s=>['restricted','confidential'].includes(s.sensitivity));
 const candidate=intervention?.audit?.action||p.action;
 const outcome=events.findLast(e=>e.type==='task_success'||e.type==='task_failure');
 const entries=[
 ['1 · Attack source',hostile.length?hostile.map(sourceLabel).join(', '):'No untrusted source linked in this decision; inspect retrieved evidence.'],
 ['2 · Sensitive item',sensitive.length?sensitive.map(s=>sourceLabel(s)+' · '+s.sensitivity).join(', '):'No classified item linked in this decision.'],
 ['3 · Attempted action',candidate?(candidate.tool||candidate.type)+(candidate.arguments?.to?' → '+candidate.arguments.to:''):'No intervention recorded.'],
 ['4 · AEGIS reason',p.explanation||'No intervention recorded; this alone does not establish protection.'],
 ['5 · Enforcement',p.decision?p.decision.toUpperCase()+(p.rewritten_action?' · replacement recorded':''):'No intervention'],
 ['6 · Task outcome',outcome?outcome.payload.summary+' · '+outcome.payload.termination:'No graded outcome recorded in this trace.']
 ];
 entries.forEach(([label,text])=>{const card=el('div',undefined,'story-card');card.append(el('strong',label),el('p',text));node.append(card)});
}
